/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFirmwareRouteImport } from './routes/_app/firmware'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppHardwareRouteImport } from './routes/_app/hardware'
import { Route as AppHerdRouteImport } from './routes/_app/herd'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppRiskMapRouteImport } from './routes/_app/risk-map'
import { Route as AppSensorsRouteImport } from './routes/_app/sensors'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAnimalAnimalIdRouteImport } from './routes/_app/animal.$animalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFirmwareRoute = AppFirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppHardwareRoute = AppHardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => AppRoute,
} as any)
const AppHerdRoute = AppHerdRouteImport.update({
  id: '/herd',
  path: '/herd',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskMapRoute = AppRiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => AppRoute,
} as any)
const AppSensorsRoute = AppSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalAnimalIdRoute = AppAnimalAnimalIdRouteImport.update({
  id: '/animal/$animalId',
  path: '/animal/$animalId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/firmware': typeof AppFirmwareRoute
  '/forecast': typeof AppForecastRoute
  '/hardware': typeof AppHardwareRoute
  '/herd': typeof AppHerdRoute
  '/history': typeof AppHistoryRoute
  '/risk-map': typeof AppRiskMapRoute
  '/sensors': typeof AppSensorsRoute
  '/settings': typeof AppSettingsRoute
  '/animal/$animalId': typeof AppAnimalAnimalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/firmware': typeof AppFirmwareRoute
  '/forecast': typeof AppForecastRoute
  '/hardware': typeof AppHardwareRoute
  '/herd': typeof AppHerdRoute
  '/history': typeof AppHistoryRoute
  '/risk-map': typeof AppRiskMapRoute
  '/sensors': typeof AppSensorsRoute
  '/settings': typeof AppSettingsRoute
  '/animal/$animalId': typeof AppAnimalAnimalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/firmware': typeof AppFirmwareRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/hardware': typeof AppHardwareRoute
  '/_app/herd': typeof AppHerdRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/risk-map': typeof AppRiskMapRoute
  '/_app/sensors': typeof AppSensorsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/animal/$animalId': typeof AppAnimalAnimalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/firmware'
    | '/forecast'
    | '/hardware'
    | '/herd'
    | '/history'
    | '/risk-map'
    | '/sensors'
    | '/settings'
    | '/animal/$animalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/firmware'
    | '/forecast'
    | '/hardware'
    | '/herd'
    | '/history'
    | '/risk-map'
    | '/sensors'
    | '/settings'
    | '/animal/$animalId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/firmware'
    | '/_app/forecast'
    | '/_app/hardware'
    | '/_app/herd'
    | '/_app/history'
    | '/_app/risk-map'
    | '/_app/sensors'
    | '/_app/settings'
    | '/_app/animal/$animalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/firmware': {
      id: '/_app/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof AppFirmwareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hardware': {
      id: '/_app/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof AppHardwareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/herd': {
      id: '/_app/herd'
      path: '/herd'
      fullPath: '/herd'
      preLoaderRoute: typeof AppHerdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk-map': {
      id: '/_app/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof AppRiskMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensors': {
      id: '/_app/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AppSensorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animal/$animalId': {
      id: '/_app/animal/$animalId'
      path: '/animal/$animalId'
      fullPath: '/animal/$animalId'
      preLoaderRoute: typeof AppAnimalAnimalIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFirmwareRoute: typeof AppFirmwareRoute
  AppForecastRoute: typeof AppForecastRoute
  AppHardwareRoute: typeof AppHardwareRoute
  AppHerdRoute: typeof AppHerdRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppRiskMapRoute: typeof AppRiskMapRoute
  AppSensorsRoute: typeof AppSensorsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAnimalAnimalIdRoute: typeof AppAnimalAnimalIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFirmwareRoute: AppFirmwareRoute,
  AppForecastRoute: AppForecastRoute,
  AppHardwareRoute: AppHardwareRoute,
  AppHerdRoute: AppHerdRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppRiskMapRoute: AppRiskMapRoute,
  AppSensorsRoute: AppSensorsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAnimalAnimalIdRoute: AppAnimalAnimalIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
